### ISSUE TITLE
Something's wrong with majority_element

### ISSUE THREAD

**Issue by mmhan** [kumar91gopi/Algorithms-and-Data-Structures-in-Ruby#10]
https://github.com/kumar91gopi/Algorithms-and-Data-Structures-in-Ruby/blob/55e3ce9279b788cf0bd416997484495a7244a692/arrays/MajorityElementInSorted.rb#L6

Considering `majority_element([3, 3, 3, 3, 4, 4, 4]` should return 3, it is currently returning -1.

**Comment by kumar91gopi** [comment]
Thanks for bringing this to notice, code has been updated. I will encourage you to try to resolve the issue yourself before looking at the updated code
